"""Compute each panorama's forward (theta=0) compass heading from the painted
stall numbers, in the MAP/SVG coordinate frame (0=up/north, 90=east, +=clockwise).

Two-sided photos: forward is perpendicular to the line joining the left- and
right-column centroids (the right column sits at forward+90). This is robust to
per-stall noise. One-sided photos inherit the heading of a two-sided sibling that
shares a painted stall (same physical block/aisle); failing that, the block is an
edge block and the aisle faces the market interior.
"""
import json, os, glob, math

HERE = os.path.dirname(__file__)
coords = json.load(open(os.path.join(HERE, '_coords.json'), encoding='utf-8'))
SVG = coords['SVG_STALL_COORDS']
SMAP = coords['STALL_MAP']
SEC = {'meat': 'meat', 'fish': 'fish', 'veg': 'veggies'}
MAP_CX = 1152

OVERRIDES = {}  # photo -> heading, for anything that still needs a manual fix

def resolve(section, num):
    secKey = SEC.get(section, section)
    key = f'{secKey}-{num}'
    if key in SVG:
        return (SVG[key]['x'], SVG[key]['y'])
    if secKey in SMAP and str(num) in SMAP[secKey]:
        c = SMAP[secKey][str(num)]
        return (c['x'], c['y'])
    return None

def _median(xs):
    s = sorted(xs); n = len(s)
    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2

def centroid(pts):
    # median per-axis: robust to the occasional inconsistent stall coordinate
    return (_median([p[0] for p in pts]), _median([p[1] for p in pts]))

def bearing(fr, to):
    return (math.degrees(math.atan2(to[0] - fr[0], -(to[1] - fr[1]))) + 360) % 360

def angdiff(a, b):
    return abs((a - b + 180) % 360 - 180)

def snap90(a):
    s = round(a / 90) * 90 % 360
    return s if angdiff(a, s) <= 35 else round(a) % 360

# merge all scan files
scan = {}
for f in sorted(glob.glob(os.path.join(HERE, 'pano_scan*.json'))):
    for k, v in json.load(open(f, encoding='utf-8')).items():
        if not k.startswith('_'):
            scan[k] = v

# resolve painted columns to coords once
prepared = {}
for photo, info in scan.items():
    left = [c for c in (resolve(*p) for p in info.get('left', [])) if c]
    right = [c for c in (resolve(*p) for p in info.get('right', [])) if c]
    # role-tagged keys so a shared stall only counts when seen from the same side
    keys = [('L', SEC.get(s, s), n) for s, n in info.get('left', [])] + \
           [('R', SEC.get(s, s), n) for s, n in info.get('right', [])]
    prepared[photo] = (left, right, keys)

# pass 1: two-sided via centroid difference
results, report = {}, []
for photo, (left, right, keys) in prepared.items():
    if left and right:
        lc, rc = centroid(left), centroid(right)
        if math.dist(lc, rc) < 1:
            continue
        fwd = (bearing(lc, rc) - 90) % 360       # right column is at forward+90
        results[photo] = snap90(fwd)
        report.append((photo, results[photo], f'2-sided raw={fwd:.0f}'))

# index: which two-sided headings touch each painted stall
stall_to_h = {}
for photo, h in results.items():
    for k in prepared[photo][2]:
        stall_to_h.setdefault(k, []).append(h)

# pass 2: one-sided -> inherit from sibling sharing a painted stall, else interior rule
for photo, (left, right, keys) in prepared.items():
    if photo in results:
        continue
    block = left or right
    if not block:
        report.append((photo, None, 'NO COORDS'))
        continue
    sib = [h for k in keys for h in stall_to_h.get(k, [])]
    if sib:
        h = max(set(sib), key=sib.count)          # majority sibling heading
        results[photo] = h
        report.append((photo, h, f'1-sided<-sibling ({len(sib)} votes)'))
    else:
        bc = centroid(block)
        interior = bc[0] + 150 if bc[0] < MAP_CX else bc[0] - 150
        cam = (interior, bc[1])
        side = -90 if left else 90
        fwd = (bearing(cam, bc) - side) % 360
        results[photo] = snap90(fwd)
        report.append((photo, results[photo], f'1-sided/interior raw={fwd:.0f}'))

results.update(OVERRIDES)

# summary
from collections import Counter
print('heading distribution:', dict(Counter(results.values())))
print('\n=== non-zero / notable ===')
for photo, h, note in sorted(report):
    if h != 0:
        print(f'{str(h):>5}  {photo:28s} {note}')

out = os.path.join(HERE, '..', 'src', 'utils', 'panoHeadings.js')
lines = ['// AUTO-GENERATED by scripts/compute_headings.py from painted stall numbers.',
         '// Forward (theta=0) compass heading per panorama file: 0=map-north, +=clockwise.',
         '// Re-run the script to regenerate; do not edit by hand.',
         'export const PANO_HEADINGS = {']
for photo in sorted(results):
    if results[photo] is not None:
        lines.append(f'  {json.dumps(photo)}: {results[photo]},')
lines.append('};')
open(out, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print('\nwrote', out, 'with', sum(v is not None for v in results.values()), 'entries')
